[tool.flake8]

extend-ignore = [
    # Styling rules already handled by black
    "E1",
    "W1",
    "E2",
    "W2",
    "E3",
    "W3",
    "E5",
    "W503",
    "W504",
    # No import at top of file: conflict with certain Data Science Packages
    "E402",
    # Do not use bare except
    "E722",
    #Docstring 
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D212"
]

per-file-ignores = '''
    __init__.py:F401
'''

max-complexity = 20

docstring-convention = "google"

max-doc-length = 160

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
preview = true
