name: Lint Checks
on: [pull_request, push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Run linting
        run: |
          make setup-env
          make lint CHECK=1
